name: sapient grid
favicon: null
layout_spectrum: 0.10813136678189039
typography_spectrum: 0.8820557836443186
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7217651882674545
  lightness: 0.892982822842896
  saturation: 0.5307377553544939
  rhythmicContrast: 0.30022843601182103
purpose: []
